title: NIR
author: NIR team
logo: ../logo_light.png

repository:
  url: https://github.com/neuromorphs/nir
  branch: main
  path_to_book: docs/source

execute:
  execute_notebooks: off

launch_buttons:
  notebook_interface: "jupyterlab"
  binderhub_url: "https://mybinder.org/v2/gh/neuromorphs/nir/main?urlpath=lab"
  colab_url: "https://colab.research.google.com"